SELECT 
U.NAMESURNAME,COUNT(A.ID) ADRESSAYISI, COUNT(DISTINCT C.COUNTRY) AS ULKESAYISI   --COUNT(DISTINCT U.USERNAME_) --DISTINCT U.NAMESURNAME
,COUNT (DISTINCT CT.ID) AS SEHIRSAYISI
FROM
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,TOWNS T,DISTRICTS D
WHERE u.ID=a.USERID 
--AND u.ID=1
AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID 
AND D.ID=A.DISTRICTID AND T.ID=A.TOWNID
GROUP BY U.NAMESURNAME
HAVING COUNT(A.ID)>2  





