SELECT 
USERS.USERNAME_,USERS.NAMESURNAME,USERS.GENDER,
USERS.TELNR1,ADDRESS.ADDRESSTEXT FROM
USERS,ADDRESS
WHERE USERS.ID=ADDRESS.USERID
AND USERS.ID=1

--ALIAS KULLANIMI

SELECT 
U.USERNAME_ AS KULLANICIADI,
U.NAMESURNAME  ADSOYAD,
U.GENDER  CINSIYET,
U.TELNR1 AS TELNO,
C.COUNTRY AS ULKE,
CT.CITY AS IL,
T.TOWN AS ILCE,
D.DISTRICT AS SEMT,
a.ADDRESSTEXT AS ADRES

FROM
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,TOWNS T,DISTRICTS D
WHERE u.ID=a.USERID 
--AND u.ID=1
AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID 
AND D.ID=A.DISTRICTID AND T.ID=A.TOWNID
AND CT.CITY LIKE 'KONYA'
ORDER BY U.USERNAME_



