SELECT 
CT.CITY,COUNT(U.ID) KULLANICISAYISI,COUNT(DISTINCT T.TOWN) ILCESAYISI,
T.TOWN,D.DISTRICT
FROM
USERS U,ADDRESS A,COUNTRIES C,CITIES CT,TOWNS T,DISTRICTS D
WHERE u.ID=a.USERID 
AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID 
AND D.ID=A.DISTRICTID AND T.ID=A.TOWNID
GROUP BY CT.CITY,T.TOWN,D.DISTRICT






