SELECT 
	U.USERNAME_ AS KULLANICIADI,
	U.NAMESURNAME AS ADSOYAD,
	CT.CITY AS SEHIR,
	T.TOWN AS ILCE,
	D.DISTRICT AS SEMT,
	A.ADDRESSTEXT AS ADRES,
	O.ID AS SIPARISID,
	O.DATE_ AS TARIH,
	O.TOTALPRICE AS TOTALPRICE,
	P.DATE_ AS ODEMETARIHI,
	P.APPROVECODE AS BANKAONAYKODU,
	I.DATE_ AS FATURATARIHI,
	I.CARGOFICHENO AS KARGOFISNO,
	IT.ITEMCODE AS URUNKODU,
	IT.ITEMNAME AS URUNADI,
	ORD.AMOUNT AS MIKTAR,
	ORD.UNITPRICE AS BIRIMFIYAT,
	ORD.LINETOTAL AS SATIRTOPLAM

FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	JOIN ADDRESS A ON A.ID=O.ADDRESSID
	JOIN CITIES CT ON CT.ID=A.CITYID
	JOIN TOWNS T ON T.ID=A.TOWNID
	JOIN DISTRICTS D ON D.ID=A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
	JOIN INVOICES I ON I.ORDERID=O.ID
	JOIN ORDERDETAILS ORD ON ORD.ORDERID=O.ID 
	JOIN ITEMS IT ON IT.ID=ORD.ITEMID
WHERE 
	O.ID='30025'
	--U.NAMESURNAME='Emrah CANBOLAT'
--SELECT COUNT(*)FROM ORDERS
