SELECT 
	--CONVERT(DATE,O.DATE_) AS SIPARISTARIH,
	--CONVERT(DATE,I.DATE_) AS TARIH,
	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) TESLIMATSURESISAAT,
	MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MIN,
	MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS MAX
	
	


FROM ORDERS O
JOIN INVOICES I ON O.ID=I.ORDERID


--SELECT DATEDIFF(DAY,'2019-12-24','2019-12-26')

