SELECT 
	AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) ORTALAMATESLIMAT,
	MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) ENKISASUREN,
	MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) EN_UZUN_SUREN,
	U.ID MUSTERIID,
	U.NAMESURNAME AS ADSOYAD,
	SUM(O.TOTALPRICE) AS TOPLAM_TUTAR,
	COUNT(O.ID) AS SIPARIS_SAYISI,
	DATEPART(MONTH,O.DATE_) AS AY,
	DATEPART(YEAR,O.DATE_) AS YIL,
	CT.CITY
FROM ORDERS O 
JOIN INVOICES I ON I.ORDERID=O.ID
JOIN USERS U ON U.ID=O.USERID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES CT ON CT.ID = A.CITYID
GROUP BY U.ID,U.NAMESURNAME,DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_),CT.CITY
HAVING AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_))>30
ORDER BY 6 DESC

