---SELECT 
	--CONVERT(DATE,O.DATE_) AS TARIH,
	--SUM(OD.LINETOTAL) AS TOPLAMSATIR,
	--SUM(OD.AMOUNT) AS MIKTAR,
	--COUNT(OD.ID) AS SIPARISSAYISI

--FROM ORDERS O
--JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
---GROUP BY CONVERT(DATE,O.DATE_)
---ORDER BY 1

SELECT 
	DATEPART(YEAR,O.DATE_) AS YIL,
	DATEPART(MONTH,O.DATE_) AS TARIH,
CASE 
	WHEN DATEPART(MONTH,O.DATE_)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,O.DATE_)=2 THEN 'SUBAT'
	WHEN DATEPART(MONTH,O.DATE_)=3 THEN 'MART'
	WHEN DATEPART(MONTH,O.DATE_)=4 THEN 'NISAN'
	WHEN DATEPART(MONTH,O.DATE_)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,O.DATE_)=6 THEN 'HAZIRAN'
	WHEN DATEPART(MONTH,O.DATE_)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,O.DATE_)=8 THEN 'AGUSTOS'
	WHEN DATEPART(MONTH,O.DATE_)=9 THEN 'EYLUL'
	WHEN DATEPART(MONTH,O.DATE_)=10 THEN 'EKIM'
	WHEN DATEPART(MONTH,O.DATE_)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,O.DATE_)=12 THEN 'ARALIK'
END AS AYADI,
	SUM(OD.LINETOTAL) AS TOPLAMSATIR,
	SUM(OD.AMOUNT) AS MIKTAR,
	COUNT(OD.ID) AS SIPARISSAYISI


FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN PAYMENTS P ON P.ORDERID=O.ID
GROUP BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)
ORDER BY DATEPART(MONTH,O.DATE_),DATEPART(YEAR,O.DATE_)