SELECT 
    DATEPART(YEAR,P.DATE_) YILLAR,
	DATEPART(MONTH,P.DATE_) AS AYLAR,
CASE 
	WHEN P.PAYMENTTYPE=1 THEN 'KART'
	WHEN P.PAYMENTTYPE=2 THEN 'HAVALE'
END AS ODEMETURU,


SUM(P.PAYMENTTOTAL) TOTALODEME
FROM PAYMENTS P
GROUP BY DATEPART(MONTH,DATE_),P.PAYMENTTYPE,DATEPART(YEAR,P.DATE_)
ORDER BY 1,2