SELECT 
	CONVERT(DATE,P.DATE_) AS TARIH,
	SUM(OD.LINETOTAL) AS TOPLAMTUTAR,
	SUM(OD.AMOUNT) AS SIPARISMIKTAR,
	COUNT(OD.ID) AS TOPLAMSIPARISSAYISI
	

FROM ORDERS O

JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN PAYMENTS P ON P.ORDERID=O.ID
GROUP BY P.DATE_ 
ORDER BY 1
