SELECT U.NAMESURNAME,U.EMAIL,A.ADDRESSTEXT,C.COUNTRY   
,CT.CITY,D.DISTRICT
FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID

ORDER BY CT.CITY

--GRUOPBY KULLANIMI
SELECT CT.CITY,COUNT(U.ID) AS USERSAYISI
FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID
JOIN CITIES CT ON CT.ID=A.CITYID
GROUP BY CT.CITY


