USE JOINTEST;
CREATE TABLE USERS
(
ID INT IDENTITY(1,1),
USERNAME VARCHAR(50)
CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED(ID ASC)
)
TRUNCATE TABLE USERS
CREATE TABLE ADDRESS
(
ID INT IDENTITY(1,1),
USERID INT ,
ADDRESSTEXT VARCHAR(50)
CONSTRAINT PK_ADDRESS PRIMARY KEY CLUSTERED(ID ASC)
)
---INNER JOIN  ORTAK TABLO DÝREK JOIN ON KOMUTU
---LEFT JOIN: SOLDAKÝ BAZ ALINARAK ONA GÖRE BÝR ORTAK TABLO OLUÞTURULUR
--SOLDAKÝNÝN TAMAMI + ORTAK NOKTALARRI GETÝR
---RIGHT JOIN: SAÐDAKÝNÝN TAMAMI + ORTAK NOKTALARRI GETÝR
--KÝMÝN SAÐ KÝMÝN SOL OLDUGU KODDA BELÝRTÝLÝR
--SAÐDAKÝNÝN TAMANINI GETÝRÝRKEN KARÞILIÐI YOKSA ORAYI BOÞ GETÝRÝR
---FULL JOIN: HER ÝKÝ KÜMENÝN ÝLÝÞKÝSÝNE BAKMAKSIZIN TAMAMINI GETÝRÝR

--INNER JOIN KULLANIMI
SELECT 
U.ID,U.USERNAME,A.ADDRESSTEXT
FROM USERS U
JOIN ADDRESS A ON U.ID=A.USERID

--LEFT JOIN KULLANIMI
SELECT 
U.USERNAME, A.ADDRESSTEXT
FROM USERS U LEFT 
JOIN ADDRESS A ON U.ID=A.USERID

--RIGHT JOIN KULLANIMI
SELECT 
U.USERNAME, A.ADDRESSTEXT
FROM USERS U 
RIGHT JOIN ADDRESS A ON U.ID=A.USERID

--FULL JOIN KULLANIMI
SELECT 
U.USERNAME, A.ADDRESSTEXT
FROM USERS U
FULL JOIN ADDRESS A ON U.ID=A.USERID
