--AGGREGATE FUNCTION
--(SUM,MÝN,MAX,AVG,AX,COUNT)

SELECT COUNT(*)FROM SALES

SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(FICHENO) FROM SALES 

SELECT COUNT(AMOUNT),SUM(AMOUNT) FROM SALES

SELECT AVG(AMOUNT) FROM SALES --ORTALAMA

SELECT SUM(TOTALPRICE),MAX(TOTALPRICE),COUNT(*),MIN(TOTALPRICE),AVG(TOTALPRICE),COUNT(TOTALPRICE) FROM SALES --TOPLAM
WHERE CITY='ÝSTANBUL'
