CREATE TABLE USERS
( ID INT IDENTITY(1,1),
USERNAME_ VARCHAR(50),
PASSWORD_ VARCHAR(50),
NAMESURNAME VARCHAR(100),
EMAIL VARCHAR(100),
GENDER VARCHAR(1),
BIRTHDATE DATE,
CREATEDATE  DATETIME,
TELNR1 VARCHAR(15),
TELNR2 VARCHAR(15)
CONSTRAINT PK_USERS PRIMARY KEY CLUSTERED(ID ASC)
)

CREATE TABLE ITEMS
(
ID INT IDENTITY(1,1),
ITEMCODE VARCHAR(50),
ITEMNAME VARCHAR(50),
UNITPRICE FLOAT,
CATEGORY1 VARCHAR(50),
CATEGORY2 VARCHAR(50),
CATEGORY3 VARCHAR(50),
CATEGORY4 VARCHAR(50),
BRAND VARCHAR(50)

CONSTRAINT PK_ITEMS PRIMARY KEY CLUSTERED (ID ASC)
)

CREATE TABLE CITIES
(ID SMALLINT IDENTITY(1,1)
,COUNTRYID INT,
CITY VARCHAR(50)
CONSTRAINT PK_CITIES PRIMARY KEY CLUSTERED (ID ASC)
)