SELECT *FROM CUSTOMERS

UPDATE CUSTOMERS
SET NATION='TR', AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())

SELECT CITY,CUSTOMERNAME FROM CUSTOMERS
WHERE CITY='KONYA' AND CUSTOMERNAME LIKE '%MEHMET%'

SELECT *FROM CUSTOMERS
WHERE CUSTOMERNAME='Irmak TAHSÝNOÐLU'

SELECT *FROM CUSTOMERS
WHERE CITY='ANKARA'

SELECT *FROM CUSTOMERS
WHERE CITY<>'ANKARA'

SELECT *FROM CUSTOMERS
WHERE NOT CITY='ANKARA'

SELECT *FROM CUSTOMERS
WHERE BIRTHDATE>'19900101'

SELECT *FROM CUSTOMERS
WHERE BIRTHDATE>='1966-02-03'

SELECT *FROM CUSTOMERS 
WHERE BIRTHDATE BETWEEN '19900101' AND '1999-02-03'

UPDATE CUSTOMERS 
SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())
WHERE AGE BETWEEN 22 AND 30

SELECT *FROM CUSTOMERS
WHERE AGE BETWEEN 20 AND 35

SELECT *FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE 'ALÝ%'

SELECT *FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%ALP'

SELECT *FROM CUSTOMERS
WHERE CUSTOMERNAME LIKE '%ALAN%'

SELECT *FROM CUSTOMERS
WHERE CITY IN ('KONYA','KARAMAN')

SELECT *FROM CUSTOMERS
WHERE DISTRICT ='KILBASAN'

UPDATE CUSTOMERS
SET GENDER='ERKEK'
WHERE GENDER='E'

SELECT *FROM CUSTOMERS WHERE ID='41'

UPDATE CUSTOMERS SET GENDER='KADIN' WHERE GENDER='K'

DELETE CUSTOMERS WHERE ID='31'