--SELECT 
--CONVERT(DATE,DATE_) AS DATE2,  --CONVERT()TÜR DÖNÜÞÜMÜ
--*FROM SALES WHERE CITY='ANKARA'
--ORDER BY DATE_

SELECT CONVERT(DATE,'2019-01-07 08:16:10.000') --SADECE TARÝH KISMINI ALIR
SELECT CONVERT(TIME,'2019-01-07 08:16:10.000') --SADECE SAAT KISMINI ALIR

SELECT *FROM SALES
UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)

SELECT *FROM SALES
WHERE CITY='ANKARA' 
ORDER BY DATE_
--MAÐAZANIN GÜN BAZLI SATIÞ RAKAMLARI
SELECT CITY,DATE2,SUM(TOTALPRICE) AS TOTAPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY CITY,DATE2
ORDER BY DATE2 

--MAÐAZANIN SATIÞ BAZLI GÜNLERÝ
SELECT DATE2,CITY,SUM(TOTALPRICE) AS TOTALPRIECE
FROM SALES WHERE DATE2='2019-01-01'
GROUP BY DATE2,CITY
ORDER BY DATE2,SUM(TOTALPRICE) DESC

--MAÐAZALARIN AYLARA GÖRE SATIÞ RAKAMLARI
SELECT *FROM SALES
SELECT DATEPART(MONTH,'1990-07-01')


UPDATE SALES SET MONTHNAME_='01 OCAK' WHERE DATEPART(MONTH,DATE2)=1
UPDATE SALES SET MONTHNAME_='02 SUBAT' WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_='03 MART' WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_='04 NÝSAN' WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_='05 MAYIS' WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_='06 HAZÝRAN' WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_='07 TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_='08 AGUSTOS' WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_='09 EYLÜL' WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_='10 EKÝM' WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_='11 KASIM' WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_='12 ARALIK' WHERE DATEPART(MONTH,DATE2)=12

SELECT MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
GROUP BY MONTHNAME_
ORDER BY MONTHNAME_ 

SELECT CITY,MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_ ,SUM(TOTALPRICE) DESC

--iLLERÝN AYLARA GÖRE SATIÞ RAKAMLARI
SELECT CITY, MONTHNAME_,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
GROUP BY CITY,MONTHNAME_
ORDER BY CITY,MONTHNAME_,SUM(TOTALPRICE)

SELECT MONTHNAME_,CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
GROUP BY MONTHNAME_,CITY
ORDER BY MONTHNAME_,SUM(TOTALPRICE) DESC




SELECT *FROM SALES