SELECT *FROM CUSTOMERS

WHERE CITY='ÝSTANBUL' OR CITY='ÝZMÝR' OR CITY='BURSA'
--YORUM SATIRI
SELECT*FROM CUSTOMERS
WHERE CITY IN('ISTANBUL','BURSA')

SELECT*FROM CUSTOMERS
WHERE BIRTHDATE >='19900101' AND BIRTHDATE <='20001010'

SELECT *FROM CUSTOMERS
WHERE NOT BIRTHDATE BETWEEN '19900101' AND '20000101'

--DISCINCT
--AYNI DEGERE SAHÝP OLANLARI 1 KERE GETÝR

SELECT DISTINCT CITY,DISTRICT FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'

SELECT DISTINCT GENDER FROM CUSTOMERS

SELECT DISTINCT AGE FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'

SELECT DISTINCT AGE FROM CUSTOMERS
WHERE CITY='KONYA'

SELECT DISTINCT BIRTHDATE,CITY,CUSTOMERNAME FROM CUSTOMERS