SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND DISTRICT='Beylikdüzü' AND AGE='25'

SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' 
AND DISTRICT='BEYLÝKDÜZÜ' OR DISTRICT='ESENLER'

SELECT *FROM CUSTOMERS 
WHERE CITY='KARAMAN' OR AGE='45'

SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND GENDER='ERKEK' AND DISTRICT='ESENLER'

SELECT *FROM CUSTOMERS
WHERE CITY='ÝSTANBUL' AND GENDER='ERKEK'
AND BIRTHDATE BETWEEN '1990-01-01' AND '2000-01-01'

SELECT *FROM CUSTOMERS