--GRUOPBY KULLANIMI
SELECT 
CITY,
SUM(TOTALPRICE) AS TOTALPRICE
,MAX(TOTALPRICE) AS MAXPRICE
,MIN(TOTALPRICE) AS MINPRICE
,AVG(TOTALPRICE) AS ORTALAMA
,COUNT(*) AS ROWCOUNT_

FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) 


SELECT TOP 10 
CITY,AMOUNT, SUM(TOTALPRICE) AS TOPLAMPRICE FROM SALES
GROUP BY CITY,AMOUNT
ORDER BY SUM(TOTALPRICE) DESC