SELECT 
CITY,COUNT(DISTINCT(FICHENO)) AS MUSTERISAYISI,COUNT(*) AS BARKODSAYISI
FROM SALES WHERE MONTHNAME_='01 OCAK'
GROUP BY CITY
ORDER BY CITY

SELECT 
CITY,COUNT(DISTINCT(CUSTOMERNAME)) AS TEKILMUSTERI, COUNT(DISTINCT(FICHENO)) AS MUSTERISAYISI,COUNT(*) AS BARKODSAYISI
FROM SALES WHERE MONTHNAME_='01 OCAK'
GROUP BY CITY
ORDER BY CITY

--BELLÝ BÝR CÝRONUN ÜZERÝNDE SATIÞ YAPAN MAÐAZALAR

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE FROM SALES
WHERE SUM(TOTALPRICE)>40000 --HATA VERÝR
GROUP BY CITY
ORDER BY CITY,SUM(TOTALPRICE)

SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE,COUNT(DISTINCT(CUSTOMERNAME)) AS MUSTERISAYISI FROM SALES
WHERE CITY IN('ANKARA','ÝSTANBUL','HATAY','KONYA','ÝZMÝR')
GROUP BY CITY
HAVING SUM(TOTALPRICE)>40000 AND COUNT(DISTINCT(CUSTOMERNAME))>2000

ORDER BY SUM(TOTALPRICE) DESC