SELECT CATEGORY2,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS COUNTS,
SUM(AMOUNT) AS AMOUNTS

FROM SALES
GROUP BY CATEGORY2
ORDER BY CATEGORY2



SELECT CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(*) AS COUNTS,
SUM(AMOUNT) AS AMOUNTS

FROM SALES
GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4
ORDER BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4