--ORDER BY
--SIRALI GETÝR KOMUTU 
--ASC:KÜÇÜKTEN BÜYÜÐE(DEFAULT) , DESC:BÜYÜKTEN KÜÇÜÐE

SELECT *FROM CUSTOMERS
ORDER BY CUSTOMERNAME DESC


SELECT *FROM CUSTOMERS
ORDER BY BIRTHDATE DESC

SELECT *FROM CUSTOMERS
ORDER BY CITY,CUSTOMERNAME DESC,GENDER

SELECT *FROM CUSTOMERS
ORDER BY CITY,DISTRICT,CUSTOMERNAME

SELECT*FROM CUSTOMERS
WHERE CITY='ÝSTANBUL'
ORDER BY DISTRICT,CUSTOMERNAME

SELECT*FROM CUSTOMERS
WHERE CITY='KONYA'
ORDER BY 2 --(CUSTOMERNAME)

--TOP
--BÜYÜK VERÝLERÝN BÝR KISMINI GÖSTERMEYE YARAR
SELECT TOP 100 * FROM CUSTOMERS --100 SATIR GETÝTÝR

SELECT TOP 100 *FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT
TOP 45 PERCENT  --%45 ÝNÝ GETÝRÝR
*FROM CUSTOMERS
ORDER BY CUSTOMERNAME