SELECT 
ID, [CUSTOMERNAME], [CITY], [DISTRICT], [BIRTHDATE], [GENDER]
FROM
CUSTOMERS

INSERT INTO CUSTOMERS
(CUSTOMERNAME, CITY, DISTRICT, BIRTHDATE, GENDER)
VALUES
('MEHMET ALÝ', 'KARAMAN', 'GILBASAN', '2000-05-19', 'E');



