--ASCII GÝRÝLEN DEGERÝN ACSII KODUNU GETÝRÝR
SELECT ASCII('A')
SELECT ASCII('3')
--CHAR ASCII KODUN CHAR KARSILIGINI GETÝRÝR
SELECT CHAR(65)
SELECT ASCII(CHAR(214))
SELECT CHAR(ASCII('Ö'))

--SUBSTRING
SELECT SUBSTRING('MEHMET YUSUF BIRCAN',8,5) --*DAN ÝTÝBAREN *KERE AL

