--KULLANICININ SON ADRESÝNÝ BULMA
SELECT U.NAMESURNAME, (SELECT TOP 1 ADDRESSTEXT FROM ADDRESS A WHERE A.USERID=U.ID ORDER BY A.ID DESC) AS SONADRES,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS A WHERE A.USERID=U.ID ORDER BY A.ID) AS ILKADRES,
(SELECT COUNT(A.ID) FROM ADDRESS A WHERE A.USERID=U.ID) AS ADRESSAYISI
FROM USERS U
