--URUNLERÝN FÝYAT ALANLÝZÝ
--SUBQUERY:DURUMLARA GÖRE KULALNILIR.
SET STATISTICS IO ON  --BELLEKTEN NE KADAR VER OKUR, JOIN KULLANMAK DAHA VERÝMLÝDÝR
SELECT ITM.ITEMCODE AS URUNKODU,
ITM.ITEMNAME AS URUNADI,
(SELECT MIN(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUK,
(SELECT MAX(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ENDUSUK,
(SELECT AVG(UNITPRICE) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS ORTALAMA,
(SELECT SUM(AMOUNT) FROM ORDERDETAILS WHERE ITEMID=ITM.ID) AS TOPLAMSATIS


FROM ITEMS ITM
ORDER BY ITM.ITEMNAME